### ISSUE TITLE
Build on Ubuntu16.04 requires several dependencies not satisfied by install_deps.sh

### ISSUE THREAD

**Issue by hmacdope** [LLNL/MemSurfer#1]
The GMP package and MPFR packages are required to build the CGAL core libraries and are not installed prior to the attempted CGAL compile.

Manual installation of GMP and MPFR may be required on some platforms, or possibly circumvented by installing CGAL using apt
"sudo apt-get install libcgal-dev" 

and pointing MemSurfer in the right direction using
export CGAL_ROOT=<path_to_cgal>

Other than that thanks for all the hard work.

**Comment by bhatiaharsh** [comment]
thank you for pointing this out. i was indeed using those without realizing. I have not explicitly noted this down in the readme.
