### ISSUE TITLE
Adding MemSurfer to Conda

### ISSUE THREAD

**Issue by p-j-smith** [LLNL/MemSurfer#5]
Hi, thanks for the very nice package! I am just wondering whether you have any plans to make it available via Conda, specifically the [conda-forge](https://conda-forge.org/docs/maintainer/adding_pkgs.html) channel? I have not added pacakges to Conda before, but would be happy to help figure out how so that others can more easily install MemSurfer.

**Comment by bhatiaharsh** [comment]
Thanks for the note. I do not have plans to add this to conda right now, so if you'd want to contribute, please do so. I appreciate that.

**Comment by p-j-smith** [comment]
I had a look and it seems that, for a package to be added to conda-forge, all external dependencies must already be available through conda-forge. So unfortunately adding MemSurfer to conda-forge is not possible right now, but thanks again for this cool package.
