### ISSUE TITLE
issue with importing memsurfer after installing with spack. 

### ISSUE THREAD

**Issue by Satya-Chaithanya-Duggisetty** [LLNL/MemSurfer#8]
Python 3.7.7 (default, Jul 25 2020, 19:09:04)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import memsurfer
Traceback (most recent call last):
  File "/home/satya/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/memsurfer-1.0-5jeqsygjzxqh2bgh3sjq7wuljfgaiu5o/lib/python3.7/site-packages/memsurfer-1.0.0-py3.7-linux-x86_64.egg/memsurfer/pymemsurfer.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/satya/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/python-3.7.7-4juxjrlcplzzqfleofzbvfym2shujqqz/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'memsurfer._pymemsurfer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/satya/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/memsurfer-1.0-5jeqsygjzxqh2bgh3sjq7wuljfgaiu5o/lib/python3.7/site-packages/memsurfer-1.0.0-py3.7-linux-x86_64.egg/memsurfer/__init__.py", line 15, in <module>
    from .membrane import Membrane
  File "/home/satya/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/memsurfer-1.0-5jeqsygjzxqh2bgh3sjq7wuljfgaiu5o/lib/python3.7/site-packages/memsurfer-1.0.0-py3.7-linux-x86_64.egg/memsurfer/membrane.py", line 21, in <module>
    from . import pymemsurfer
  File "/home/satya/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/memsurfer-1.0-5jeqsygjzxqh2bgh3sjq7wuljfgaiu5o/lib/python3.7/site-packages/memsurfer-1.0.0-py3.7-linux-x86_64.egg/memsurfer/pymemsurfer.py", line 17, in <module>
    _pymemsurfer = swig_import_helper()
  File "/home/satya/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/memsurfer-1.0-5jeqsygjzxqh2bgh3sjq7wuljfgaiu5o/lib/python3.7/site-packages/memsurfer-1.0.0-py3.7-linux-x86_64.egg/memsurfer/pymemsurfer.py", line 16, in swig_import_helper
    return importlib.import_module('_pymemsurfer')
  File "/home/satya/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/python-3.7.7-4juxjrlcplzzqfleofzbvfym2shujqqz/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/satya/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/memsurfer-1.0-5jeqsygjzxqh2bgh3sjq7wuljfgaiu5o/lib/python3.7/site-packages/memsurfer-1.0.0-py3.7-linux-x86_64.egg/_pymemsurfer.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __gmpq_add

I have installed memsurfer using spack. GMP and MPFR were installed in the machine.  when i was looking for solution, found this thread in the issues (https://github.com/LLNL/MemSurfer/issues/3) but i don't know how to implement this with spack. 

Best regards
Satya Chaithanya

**Comment by bhatiaharsh** [comment]
Hello Satya, I am not able to reproduce the issue. spack installation should automatically pick the gmp and mpfr used for compiling cgal and memsurfer. Can you send me the output of `spack find -dvl memsurfer` ?

By default, spack will install gmp and mpfr for you. But you say that they were installed on the machine, so did you make any modifications to point spack to those installations? Can you tell me what steps did you take exactly?

**Comment by Satya-Chaithanya-Duggisetty** [comment]
outpur of spack find -dvl memsurfer,


==> 1 installed package
-- linux-ubuntu18.04-haswell / gcc@7.5.0 ------------------------
5jeqsyg memsurfer@1.0+osmesa
24fxyg6     cgal@4.13~core~demos~imageio+shared build_type=Release
2qo6my3         boost@1.73.0+atomic+chrono~clanglibcpp~container~context~coroutine+date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave cxxstd=98 patches=246508e052c44b6f4e8c2542a71c06cacaa72cd1447ab8d2a542b987bc35ace9,4dd507e1f5a29e3b87b15321a4d8c74afdc8331433edabf7aeab89b3c405d556 visibility=hidden
odnxdc3             bzip2@1.0.8+shared
zkl5ufy             zlib@1.2.11+optimize+pic+shared
66a4wp2         gmp@6.1.2
i5c35gu         mpfr@4.0.2 patches=3f80b836948aa96f8d1cb9cc7f3f55973f19285482a96f9a4e1623d460bcccf0
h325s5c     eigen@3.3.7 build_type=RelWithDebInfo
zjpbg5v     hdf5@1.10.6~cxx~debug~fortran+hl~mpi+pic+shared~szip~threadsafe api=none
7ibpulp     py-numpy@1.19.1+blas+lapack
qzy5vz5         openblas@0.3.10~consistent_fpcsr~ilp64+pic+shared threads=none
4juxjrl         python@3.7.7+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87
3sylp4j             expat@2.2.9+libbsd
fzzuj57                 libbsd@0.10.0
7xayw7d             gdbm@1.18.1
m223ipe                 readline@8.0
yillvg4                     ncurses@6.2~symlinks+termlib
3nufwnh             gettext@0.20.2+bzip2+curses+git~libunistring+libxml2+tar+xz
dtlc732                 libiconv@1.16
5ocv57r                 libxml2@2.9.10~python
3q6gncb                     xz@5.2.5
ubjpbg3                 tar@1.32
pmtijtm             libffi@3.3 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0
7pplabt             openssl@1.1.1g+systemcerts
yalztzz             sqlite@3.31.1+column_metadata+fts~functions~rtree
2u3pqv3     vtk@8.1.2~ffmpeg~mpi+opengl2+osmesa+python~qt~xdmf build_type=RelWithDebInfo
jsmrog5         freetype@2.10.1
6jvpgru             libpng@1.6.37
2vn7r7c         glew@2.0.0
qhkn2hm             libice@1.0.9
miiqmwu             libsm@1.2.2
zgpiqr5                 libuuid@1.0.3
vtay7am             mesa@18.3.6+glx+llvm+opengl~opengles+osmesa patches=55a5611ca9fcbe8324c4d68a07b338134954ff12c5b122dc78ff376f012a1414 swr=none
mo4rpsp                 libx11@1.6.7
35iul4o                     kbproto@1.0.7
2juhxb4                     libxcb@1.13
ahhyn3z                         libpthread-stubs@0.4
t2lao5s                         libxau@1.0.8
hl5jkoc                             xproto@7.0.31
qt76not                         libxdmcp@1.1.2
rxfy3dr                     xextproto@7.3.0
55vjugr                 libxext@1.3.3
6gf2acu                 llvm@10.0.0~all_targets+clang~code_signing+compiler-rt~cuda+gold+internal_unwind+libcxx+lld+lldb~mlir~omp_debug~omp_tsan+polly~python~shared_libs~split_dwarf build_type=Release cuda_arch=none patches=332fe65f78b2b4a242045ec2394eee8db631fbcbe27b0016d5e5c859e34f47af
h2xcnnn                     binutils@2.34+gold~headers~interwork~ld~libiberty~lto+nls~plugins
x7yadtu                     hwloc@2.2.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml+pci+shared
zlvpt6m                         libpciaccess@0.13.5
eas54lx                     libedit@3.1-20191231
apld5vq                     swig@3.0.12
hjqurur                         pcre@8.44~jit+multibyte+utf
n7xqhzb                     z3@4.8.7+python
zd3a3pc                         py-setuptools@46.1.3
t5ylwte         jsoncpp@1.9.2 build_type=RelWithDebInfo cxxstd=default
6pm27f7         libjpeg-turbo@2.0.4
npoknir         libtiff@4.0.10
qjdxaef         lz4@1.9.2
zb3a3wj         netcdf-c@4.7.3~dap~hdf4~jna~mpi~parallel-netcdf+pic+shared
dzhqsc3         netcdf-cxx@4.2+netcdf4



I haven't changed any modifications to point spack to gmp or mpfr installations, I don't remember the name of the package, one of the package constantly getting terminated without getting installed using spack. when i kept the error in online i got comand line solution to install gmp and mpfr. Then the package got installed.
